name: Manual trigger
on:
  workflow_call:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
        type: string
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Hello Step
            run: echo "Hello ${{ github.event.inputs.name }}"
